name: "publish package"

on:
  push:
    branches:
      - master

jobs:
  PublishPackage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci

      -name: Build Package
        run: npm run build
        
      -name: Publish package
        run: npm publish